### ISSUE TITLE
README.md文件中的链接404

### ISSUE THREAD

**Issue by Z4HD** [liwanglin12/LWL-API#4]
故障链接：https://blog.lwl12.com/read/2016-stop-service.html

**Comment by liwanglin12** [comment]
因为文章撤了。。
这个仓库被Fork了几份就没打算撤了

**Comment by Z4HD** [comment]
说实话，我根据链接的字面意思大致猜出来那是个API停运说明的页面？

**Comment by liwanglin12** [comment]
嗯，年度简报里有提到
